FROM nginx:latest

# 从上个包里copy打包好的文件
COPY dist/ /usr/share/nginx/html

# copy本地的配置文件
COPY ~/nginx/conf/nginx.conf /etc/nginx/nginx.conf

# 设置时区
ENV TZ="Asia/Shanghai"

# 暴露80端口
EXPOSE 8081

# 执行命令
CMD ["nginx", "-g", "daemon off;"]
#...
